[base]
log_level = "DEBUG"
debug = false
collect = true
"职业技能按键" = "v"
"未充能近战按键" = "k"
"跳隐身按键" = "x"
"终结技按键" = "g"
"埋头表情按键" = "up" # 引号里可以填写up/right/down/left


[1440p]
"开boss鼠标偏移" = [-42, -40]
"隐身后往左走时间" = 0.5
"隐身后往前走时间" = 1.83

"射击黄血鼠标偏移" = [188, 74]
"等待黄血刷新时间" = 5.815

"躲藏第一段位移镜头偏移" = [-850, 0]
"躲藏第一段位移时间" = 1.8

"躲藏第二段位移镜头偏移" = [250, 0]
"躲藏第二段位移时间" = 3


[1080p]
"开boss鼠标偏移" = [-42, -40]
"隐身后往左走时间" = 1.2
"隐身后往前走时间" = 1.52

"射击黄血鼠标偏移" = [-295, 164]
"等待黄血刷新时间" = 5.905

"躲藏第一段位移镜头偏移" = [-350, 0]
"躲藏第一段位移时间" = 2.15

"躲藏第二段位移镜头偏移" = [210, 0]
"躲藏第二段位移时间" = 3